# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protoc.re_pb2 as re__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.re = channel.unary_unary(
                '/re.API/re',
                request_serializer=re__pb2.reRequest.SerializeToString,
                response_deserializer=re__pb2.reResponse.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def re(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            're': grpc.unary_unary_rpc_method_handler(
                    servicer.re,
                    request_deserializer=re__pb2.reRequest.FromString,
                    response_serializer=re__pb2.reResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            're.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def re(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/re.API/re',
            re__pb2.reRequest.SerializeToString,
            re__pb2.reResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
