# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: re.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='re.proto',
  package='re',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08re.proto\x12\x02re\"\x1d\n\treRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"r\n\nreResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.re.reResponse.triple\x1a<\n\x06triple\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t2*\n\x03\x41PI\x12#\n\x02re\x12\r.re.reRequest\x1a\x0e.re.reResponseb\x06proto3'
)




_REREQUEST = _descriptor.Descriptor(
  name='reRequest',
  full_name='re.reRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='re.reRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=45,
)


_RERESPONSE_TRIPLE = _descriptor.Descriptor(
  name='triple',
  full_name='re.reResponse.triple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='re.reResponse.triple.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicate', full_name='re.reResponse.triple.predicate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object', full_name='re.reResponse.triple.object', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=161,
)

_RERESPONSE = _descriptor.Descriptor(
  name='reResponse',
  full_name='re.reResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='re.reResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RERESPONSE_TRIPLE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=161,
)

_RERESPONSE_TRIPLE.containing_type = _RERESPONSE
_RERESPONSE.fields_by_name['results'].message_type = _RERESPONSE_TRIPLE
DESCRIPTOR.message_types_by_name['reRequest'] = _REREQUEST
DESCRIPTOR.message_types_by_name['reResponse'] = _RERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

reRequest = _reflection.GeneratedProtocolMessageType('reRequest', (_message.Message,), {
  'DESCRIPTOR' : _REREQUEST,
  '__module__' : 're_pb2'
  # @@protoc_insertion_point(class_scope:re.reRequest)
  })
_sym_db.RegisterMessage(reRequest)

reResponse = _reflection.GeneratedProtocolMessageType('reResponse', (_message.Message,), {

  'triple' : _reflection.GeneratedProtocolMessageType('triple', (_message.Message,), {
    'DESCRIPTOR' : _RERESPONSE_TRIPLE,
    '__module__' : 're_pb2'
    # @@protoc_insertion_point(class_scope:re.reResponse.triple)
    })
  ,
  'DESCRIPTOR' : _RERESPONSE,
  '__module__' : 're_pb2'
  # @@protoc_insertion_point(class_scope:re.reResponse)
  })
_sym_db.RegisterMessage(reResponse)
_sym_db.RegisterMessage(reResponse.triple)



_API = _descriptor.ServiceDescriptor(
  name='API',
  full_name='re.API',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='re',
    full_name='re.API.re',
    index=0,
    containing_service=None,
    input_type=_REREQUEST,
    output_type=_RERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['API'] = _API

# @@protoc_insertion_point(module_scope)
