# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationExtractService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relationExtractService.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007./pb;pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1crelationExtractService.proto\x12\x05proto\"*\n\x16relationExtractRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"\x83\x01\n\x17relationExtractResponse\x12\x36\n\x07triples\x18\x01 \x03(\x0b\x32%.proto.relationExtractResponse.triple\x1a\x30\n\x06triple\x12\x0b\n\x03sub\x18\x01 \x01(\t\x12\x0c\n\x04pred\x18\x02 \x01(\t\x12\x0b\n\x03obj\x18\x03 \x01(\t2j\n\x16relationExtractService\x12P\n\rExtractTriple\x12\x1d.proto.relationExtractRequest\x1a\x1e.proto.relationExtractResponse\"\x00\x42\tZ\x07./pb;pbb\x06proto3'
)




_RELATIONEXTRACTREQUEST = _descriptor.Descriptor(
  name='relationExtractRequest',
  full_name='proto.relationExtractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='proto.relationExtractRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=81,
)


_RELATIONEXTRACTRESPONSE_TRIPLE = _descriptor.Descriptor(
  name='triple',
  full_name='proto.relationExtractResponse.triple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sub', full_name='proto.relationExtractResponse.triple.sub', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pred', full_name='proto.relationExtractResponse.triple.pred', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obj', full_name='proto.relationExtractResponse.triple.obj', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=215,
)

_RELATIONEXTRACTRESPONSE = _descriptor.Descriptor(
  name='relationExtractResponse',
  full_name='proto.relationExtractResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='triples', full_name='proto.relationExtractResponse.triples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RELATIONEXTRACTRESPONSE_TRIPLE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=215,
)

_RELATIONEXTRACTRESPONSE_TRIPLE.containing_type = _RELATIONEXTRACTRESPONSE
_RELATIONEXTRACTRESPONSE.fields_by_name['triples'].message_type = _RELATIONEXTRACTRESPONSE_TRIPLE
DESCRIPTOR.message_types_by_name['relationExtractRequest'] = _RELATIONEXTRACTREQUEST
DESCRIPTOR.message_types_by_name['relationExtractResponse'] = _RELATIONEXTRACTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

relationExtractRequest = _reflection.GeneratedProtocolMessageType('relationExtractRequest', (_message.Message,), {
  'DESCRIPTOR' : _RELATIONEXTRACTREQUEST,
  '__module__' : 'relationExtractService_pb2'
  # @@protoc_insertion_point(class_scope:proto.relationExtractRequest)
  })
_sym_db.RegisterMessage(relationExtractRequest)

relationExtractResponse = _reflection.GeneratedProtocolMessageType('relationExtractResponse', (_message.Message,), {

  'triple' : _reflection.GeneratedProtocolMessageType('triple', (_message.Message,), {
    'DESCRIPTOR' : _RELATIONEXTRACTRESPONSE_TRIPLE,
    '__module__' : 'relationExtractService_pb2'
    # @@protoc_insertion_point(class_scope:proto.relationExtractResponse.triple)
    })
  ,
  'DESCRIPTOR' : _RELATIONEXTRACTRESPONSE,
  '__module__' : 'relationExtractService_pb2'
  # @@protoc_insertion_point(class_scope:proto.relationExtractResponse)
  })
_sym_db.RegisterMessage(relationExtractResponse)
_sym_db.RegisterMessage(relationExtractResponse.triple)


DESCRIPTOR._options = None

_RELATIONEXTRACTSERVICE = _descriptor.ServiceDescriptor(
  name='relationExtractService',
  full_name='proto.relationExtractService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=217,
  serialized_end=323,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractTriple',
    full_name='proto.relationExtractService.ExtractTriple',
    index=0,
    containing_service=None,
    input_type=_RELATIONEXTRACTREQUEST,
    output_type=_RELATIONEXTRACTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RELATIONEXTRACTSERVICE)

DESCRIPTOR.services_by_name['relationExtractService'] = _RELATIONEXTRACTSERVICE

# @@protoc_insertion_point(module_scope)
