# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import relationExtractService_pb2 as relationExtractService__pb2


class relationExtractServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractTriple = channel.unary_unary(
                '/proto.relationExtractService/ExtractTriple',
                request_serializer=relationExtractService__pb2.relationExtractRequest.SerializeToString,
                response_deserializer=relationExtractService__pb2.relationExtractResponse.FromString,
                )


class relationExtractServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractTriple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_relationExtractServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractTriple': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractTriple,
                    request_deserializer=relationExtractService__pb2.relationExtractRequest.FromString,
                    response_serializer=relationExtractService__pb2.relationExtractResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.relationExtractService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class relationExtractService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractTriple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.relationExtractService/ExtractTriple',
            relationExtractService__pb2.relationExtractRequest.SerializeToString,
            relationExtractService__pb2.relationExtractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
